dist: bionic
language: python
python:
- 3.7
cache:
- apt
env:
  global:
  - secure: yML8hsf7JHjzn0rgtfr0i+TTxCijVUb3xbvWtB5grcRtoflSEgyzIRg8aZVJ7vJZqP6aYqtLojV8oVJpFcEkQu2MCt4WW2j0Lt9k7NeZN/foeoP/KNHV5YNlmS8UNReZ1OGOsqxLLI2/nRJKL9yMqLuuOD2enCLOp46hS+BxpzTyLrij0c62lQcgiK5QkJ2/Ge2MoEYQnqOKIt+QZo8exjyFBB2MAbE2hfp76dbKaGNdwVExSukeEBPX0EVDHXmgoATDoqMKfBdXwiukn2hKsK8JPz62uukvhSMh+GvBL6UauZduK5IaCglphZu0c8MbzOWHIU6p0i6T3rnQ1UtVM6mDUf2v1afRDE8YCT7K5FYhsAuFsMGFXJ9sxUHhMbzwguQp9Go8DU28vxDtUALfNHpB8gPVcEc7ddOdFjKVVsvqRbwRckEG4kgbK/zTZkNMbmUoer0eWWmPb/0rXkJidmQtOuOHzHMfKcdFcU8Mxi+xjnIQ8i/gM9cM5l5xb1Qlaln6Q72y7TQT2CCSuRfDaS2+HI4Aa0MpFIisu3jqI1SgSzV3aeZ7/77oJ/C6nXD/6cw0GiAikXrI/SilTcj9gBImxbr/t1aYwYLIzmbR8TQI0RSX4o7X0o4crUxcubloVfV5wbenlrp5Cd1Txlg1ai09WgIwLtTfWkjeiujQEYU=
install:
- travis_retry pip install pelican
- travis_retry pip install beautifulsoup4
script:
- make clean
- make DEBUG=1 RELATIVE=1 publish
- |
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
    bash travis_deploy.sh
  fi
